### ISSUE TITLE
Could this be made portable?

### ISSUE THREAD

**Issue by SteveALee** [davidebbo/WAWSDeploy#20]
This is the ONLY CLI command I have found that lets you sync from local project to Azure Files. Eg Azure Functions

Now .NET Core 2.0 spec has finalised and a preview SDK is available could this be made portable?

One obvious change in addition to rebuild is changing the option switch char from / to -.

**Comment by davidebbo** [comment]
Please see http://blog.davidebbo.com/2014/03/WAWSDeploy.html. wawdeploy is just a wrapper on top of msdeploy (`Microsoft.Web.Deployment.dll`) to make the command line more approachable. So in order to run wawsdeploy to run on Core, msdeploy would have to support it, and that may not be easy (and it's not OSS).

So... I love the goal, but there are challenges.

**Comment by SteveALee** [comment]
Yeah, I expected as much.

I've found WSASDeploy to work beautifully in my [npm  based deployment](http://azureserverless.com/2017/08/12/deploying-to-azure-functions-from-npm-scripts/) but as windows only is not suitable for publishing in my oss project. Plus I'm switching to WSL once links/junctions work
